services:
  timescaledb:
    build: .
    container_name: TSdatabase
    ports: 
      - "${DATABASE_PORT}:5432"
    environment: 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
      - ./Migrations:/docker-entrypoint-initdb.d
    restart: always

  dash-frontend:
    build:
      context: ../Frontend
    container_name: Frontend
    ports:
      - "${FRONTEND_PORT}:8050"
    depends_on:
      - timescaledb
    environment:
      DB_HOST: ${DB_HOST}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

  backend:
    build:
      context: ../Backend
      dockerfile: Dockerfile
      args:
        - BACKEND_PORT=${BACKEND_PORT}
    container_name: Backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      - timescaledb
    env_file:
      - ../Backend/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

  simulator:
    build:
      context: ../Simulator
    container_name: Simulator
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Add this line
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - SIMULATOR_PORT=${SIMULATOR_PORT}
    ports:
      - "${SIMULATOR_PORT}:8150"
    depends_on:
      - timescaledb
    restart: no

volumes:
  timescaledb_data:
