services:
  timescaledb:
    build: .
    container_name: TSdatabase
    ports: 
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    environment: 
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
      - ./Migrations:/docker-entrypoint-initdb.d
    restart: always

  dash-frontend:
    build:
      context: ../Frontend
    container_name: Frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    depends_on:
      - timescaledb
    environment:
      DB_HOST: ${DATABASE_HOST}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

  backend:
    build:
      context: ../
      dockerfile: ./Backend/Dockerfile
      args:
        - BACKEND_PORT=${BACKEND_PORT}
    container_name: Backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      - timescaledb
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

  

volumes:
  timescaledb_data:
