version: '3.8'

services:
  timescaledb:
    build: .
    container_name: TSdatabase
    ports: 
      - "5432:5432"
    environment: 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
      - ./Migrations:/docker-entrypoint-initdb.d
    restart: always

  dash-frontend:
    build:
      context: ../Frontend 
    container_name: Frontend
    ports:
      - "${FRONTEND_PORT}:8050" 
    depends_on:
      - timescaledb
    volumes:
      - ../Frontend:/app
    environment:
      - FLASK_ENV=development 
    restart: always

volumes:
  timescaledb_data:
