version: '3.8'
services:
  timescaledb:
    build: .
    container_name: timescaledb
    ports: 
      - "5432:5432"
    environment: 
      POSTGRES_PASSWORD: G5anomdet
      POSTGRES_USER: Anomdet
      POSTGRES_DB: mytimescaleDB
    volumes:
      - test:/var/lib/postgresql/data 

volumes:
  test:
    external: true
